# Generated by Django 4.1.7 on 2023-03-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('descr', models.CharField(max_length=20)),
                ('acad_groups', models.CharField(max_length=20)),
                ('careers', models.CharField(max_length=20)),
                ('campuses', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('crse_id', models.IntegerField()),
                ('strm', models.IntegerField()),
                ('session_code', models.CharField(max_length=10)),
                ('class_section', models.CharField(max_length=10)),
                ('class_nbr', models.IntegerField()),
                ('component', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('catalog_nbr', models.CharField(max_length=10)),
                ('acad_group', models.CharField(max_length=10)),
                ('class_capacity', models.IntegerField()),
                ('enrollment_total', models.IntegerField()),
                ('enrollment_available', models.IntegerField()),
                ('descr', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
