# Generated by Django 4.1.7 on 2023-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subjectclasses_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclasses',
            name='acad_group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='catalog_nbr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='class_section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='component',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='end_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='session_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='start_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
