# Generated by Django 4.1.7 on 2023-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subjectclasses_acad_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclasses',
            name='acad_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='catalog_nbr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='class_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='class_nbr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='class_section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='component',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='crse_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='end_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='enrollment_available',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='enrollment_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='session_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='start_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='strm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectclasses',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
