# Generated by Django 4.1.7 on 2023-03-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subjectclasses_days_subjectclasses_facility_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectclasses',
            name='room',
        ),
    ]
