# Generated by Django 4.1.7 on 2023-04-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(to='main.subjectclasses')),
            ],
        ),
    ]
