# Generated by Django 4.1.7 on 2023-04-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_advisorprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclasses',
            name='instructor_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
