# Generated by Django 4.1.7 on 2023-04-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subjectclasses_instructor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
