# Generated by Django 4.1.7 on 2023-04-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_userprofile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorprofile',
            name='advisor_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advisorprofile',
            name='advisor_subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advisorprofile',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_major',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
