# Generated by Django 4.1.7 on 2023-04-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_advisorprofile_advisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='instructor_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
