# Generated by Django 4.1.7 on 2023-04-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_userprofile_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_major',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
