# Generated by Django 4.1.7 on 2023-04-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_userprofile_user_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userprofile'),
        ),
    ]
