# Generated by Django 4.1.7 on 2023-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_schedule_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='schedules',
            field=models.ManyToManyField(to='main.schedule'),
        ),
    ]
