# Generated by Django 4.1.7 on 2023-04-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_schedule_user_profile_userprofile_schedules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['username']},
        ),
    ]
