# Generated by Django 4.1.7 on 2023-04-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_trigram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
    ]
