# Generated by Django 4.1.7 on 2023-05-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
