# Generated by Django 4.1.7 on 2023-05-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_schedule_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclasses',
            name='isLecture',
            field=models.BooleanField(default=True),
        ),
    ]
