# Generated by Django 4.1.7 on 2023-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_subjectclasses_islecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
